name = "NOMAD"
uuid = "02130f1c-4665-5b79-af82-ff1385104aa0"
authors = ["Alexis Montoison (@amontoison), Pierrick Pascal (@ppascal97), Ludovic Salomon (@salomonl)"]
version = "2.5.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NOMAD_jll = "2fc7fd02-576c-576e-a36a-6afce71715da"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tulip = "6dd1b50a-3aae-11e9-10b5-ef983d2400fa"

[compat]
NOMAD_jll = "= 4.5.1"
Tulip = "0.9"
julia = "1.10"
